checkpoints:
  checkpoint_interval: 500
  checkpoints_path: /path/to/models/verify-ppt/ppt-smollm3_1b
  checkpoints_path_is_shared_file_system: false
  load_lr_scheduler: true
  load_optimizer: true
  resume_checkpoint_path: null
  save_final_state: true
  save_initial_state: false
data_stages:
- data:
    dataset:
      dataset_folder:
      - /path/to/data/ppt/smollm3-baseline_v3/fineweb-edu_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/dclm_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/pes2o_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/wiki_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stackexchange_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/infiwebmath_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/finemath_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-Python_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-Java_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-JavaScript_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-C_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-Cpp_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-C-Sharp_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-PHP_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-TypeScript_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-Swift_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-SQL_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-Ruby_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-Markdown_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-HTML_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-Rust_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-Go_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-Shell_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/kaggle_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/github-issues_baseline
      dataset_read_path:
      - /path/to/data/ppt/smollm3-baseline_v3/fineweb-edu_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/dclm_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/pes2o_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/wiki_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stackexchange_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/infiwebmath_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/finemath_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-Python_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-Java_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-JavaScript_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-C_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-Cpp_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-C-Sharp_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-PHP_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-TypeScript_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-Swift_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-SQL_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-Ruby_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-Markdown_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-HTML_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-Rust_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-Go_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/stack-v2-Shell_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/kaggle_baseline
      - /path/to/data/ppt/smollm3-baseline_v3/github-issues_baseline
      dataset_weights:
      - 0.378337
      - 0.420375
      - 0.022720
      - 0.001141
      - 0.004554
      - 0.011410
      - 0.019317
      - 0.028425
      - 0.014813
      - 0.014813
      - 0.007957
      - 0.020518
      - 0.006806
      - 0.006806
      - 0.003403
      - 0.001101
      - 0.004504
      - 0.000901
      - 0.005705
      - 0.006806
      - 0.000901
      - 0.000571
      - 0.000801
      - 0.006806
      - 0.010509
      pad_samples_to_global_batch_size: false
      return_positions: true
      token_size_in_bytes: 4
      tokenizer_name: HuggingFaceTB/SmolLM3-3B
      use_old_brrr_dataloader: false
      vocab_size: 128256
    num_loading_workers: 0
    seed: 6
  name: stable
  start_training_step: 1
general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: true
  project: smollm3
  run: baseline
  seed: 6
  step: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
model:
  ddp_bucket_cap_mb: 50
  dtype: bfloat16
  init_method:
    std: 0.02
  make_vocab_size_divisible_by: 1
  model_config:
    _attn_implementation: flash_attention_2
    _fused_rms_norm: true
    _fused_rotary_emb: true
    _use_doc_masking: false
    _use_qkv_packed: true
    attention_bias: false
    bos_token_id: 128000
    eos_token_id: 128001
    flex_attention_mask: null
    hidden_act: silu
    hidden_size: 1536
    initializer_range: 0.02
    intermediate_size: 4096
    is_qwen2_config: true
    max_position_embeddings: 4096
    moe_config: null
    num_attention_heads: 12
    num_hidden_layers: 36
    num_key_value_heads: 4
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_interleaved: false
    rope_scaling: null
    rope_theta: 50000.0
    sliding_window_size: null
    tie_word_embeddings: true
    use_cache: true
    vocab_size: 128256
    no_rope_layer: null
optimizer:
  accumulate_grad_in_fp32: true
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.0005
    lr_decay_starting_step: 9000
    lr_decay_steps: 1000
    lr_decay_style: cosine
    lr_warmup_steps: 1000
    lr_warmup_style: linear
    min_decay_lr: 5.0e-05
  optimizer_factory:
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    name: adamW
    torch_adam_is_fused: true
  weight_decay: 0.1
  weight_decay_exclude_named_params: null
  zero_stage: 0
parallelism:
  context_parallel_size: 1
  dp: 4
  expert_parallel_size: 1
  moe_layer_recompute: false
  pp: 1
  pp_engine: 1f1b
  recompute_layer: false
  tp: 1
  tp_linear_async_communication: true
  tp_mode: REDUCE_SCATTER
  tp_recompute_allgather: true
profiler: null
s3_upload: null
tokenizer:
  tokenizer_max_length: 4096
  tokenizer_name_or_path: HuggingFaceTB/SmolLM3-3B
  tokenizer_revision: null
metrics_logging:
  log_level: 1
  log_detail_interval: 100
tokens:
  batch_accumulation_per_replica: 64
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 2
  sequence_length: 4096
  train_steps: 500
  val_check_interval: 100
