checkpoints:
  checkpoint_interval: 500
  checkpoints_path: /path/to/models/verify-ppt/ppt-marin_1b
  checkpoints_path_is_shared_file_system: false
  load_lr_scheduler: true
  load_optimizer: true
  resume_checkpoint_path: null
  save_final_state: true
  save_initial_state: false
data_stages:
- data:
    dataset:
      dataset_folder:
      - /path/to/data/ppt/marin-baseline_v3/dclm_marin_baseline
      - /path/to/data/ppt/marin-baseline_v3/proof-pile-algebraic-stack_baseline
      - /path/to/data/ppt/marin-baseline_v3/proof-pile-arxiv_baseline
      - /path/to/data/ppt/marin-baseline_v3/proof-pile-open-web-math_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_ada_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_agda_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_alloy_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_antlr_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_applescript_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_assembly_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_augeas_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_awk_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_batchfile_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_bluespec_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_c-sharp_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_c_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_clojure_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_cmake_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_coffeescript_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_common-lisp_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_cpp_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_css_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_cuda_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_dart_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_dockerfile_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_elixir_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_elm_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_emacs-lisp_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_erlang_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_f-sharp_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_fortran_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_git-commits-cleaned_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_github-issues-filtered-structured_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_glsl_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_go_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_groovy_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_haskell_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_html_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_idris_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_isabelle_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_java-server-pages_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_java_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_javascript_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_json_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_julia_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_jupyter-scripts-dedup-filtered_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_jupyter-structured-clean-dedup_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_kotlin_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_lean_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_literate-agda_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_literate-coffeescript_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_literate-haskell_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_lua_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_makefile_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_maple_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_markdown_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_mathematica_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_matlab_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_ocaml_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_pascal_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_perl_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_php_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_powershell_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_prolog_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_protocol-buffer_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_python_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_r_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_racket_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_restructuredtext_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_rmarkdown_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_ruby_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_rust_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_sas_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_scala_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_scheme_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_shell_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_smalltalk_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_solidity_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_sparql_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_sql_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_stan_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_standard-ml_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_stata_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_systemverilog_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_tcl_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_tcsh_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_tex_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_thrift_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_typescript_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_verilog_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_vhdl_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_visual-basic_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_xslt_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_yacc_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_yaml_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_zig_baseline
      dataset_read_path:
      - /path/to/data/ppt/marin-baseline_v3/dclm_marin_baseline
      - /path/to/data/ppt/marin-baseline_v3/proof-pile-algebraic-stack_baseline
      - /path/to/data/ppt/marin-baseline_v3/proof-pile-arxiv_baseline
      - /path/to/data/ppt/marin-baseline_v3/proof-pile-open-web-math_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_ada_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_agda_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_alloy_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_antlr_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_applescript_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_assembly_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_augeas_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_awk_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_batchfile_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_bluespec_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_c-sharp_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_c_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_clojure_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_cmake_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_coffeescript_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_common-lisp_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_cpp_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_css_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_cuda_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_dart_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_dockerfile_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_elixir_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_elm_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_emacs-lisp_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_erlang_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_f-sharp_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_fortran_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_git-commits-cleaned_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_github-issues-filtered-structured_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_glsl_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_go_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_groovy_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_haskell_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_html_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_idris_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_isabelle_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_java-server-pages_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_java_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_javascript_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_json_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_julia_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_jupyter-scripts-dedup-filtered_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_jupyter-structured-clean-dedup_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_kotlin_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_lean_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_literate-agda_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_literate-coffeescript_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_literate-haskell_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_lua_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_makefile_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_maple_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_markdown_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_mathematica_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_matlab_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_ocaml_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_pascal_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_perl_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_php_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_powershell_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_prolog_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_protocol-buffer_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_python_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_r_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_racket_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_restructuredtext_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_rmarkdown_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_ruby_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_rust_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_sas_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_scala_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_scheme_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_shell_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_smalltalk_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_solidity_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_sparql_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_sql_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_stan_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_standard-ml_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_stata_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_systemverilog_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_tcl_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_tcsh_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_tex_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_thrift_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_typescript_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_verilog_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_vhdl_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_visual-basic_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_xslt_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_yacc_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_yaml_baseline
      - /path/to/data/ppt/marin-baseline_v3/starcoderdata_zig_baseline
      dataset_weights:
      - 0.92600
      - 0.00260
      - 0.00685
      - 0.00355
      - 0.00002074
      - 0.00000549
      - 0.00000061
      - 0.00000427
      - 0.00000061
      - 0.00012383
      - 0.00000000
      - 0.00000183
      - 0.00001830
      - 0.00000244
      - 0.00355203
      - 0.00428647
      - 0.00003660
      - 0.00003599
      - 0.00005063
      - 0.00011163
      - 0.00389119
      - 0.00023851
      - 0.00004453
      - 0.00029097
      - 0.00003355
      - 0.00005673
      - 0.00002379
      - 0.00003233
      - 0.00005551
      - 0.00004880
      - 0.00014152
      - 0.00254492
      - 0.00432673
      - 0.00003172
      - 0.00189161
      - 0.00007259
      - 0.00017751
      - 0.00233508
      - 0.00000244
      - 0.00000610
      - 0.00007808
      - 0.00691496
      - 0.00514657
      - 0.00007930
      - 0.00010431
      - 0.00056608
      - 0.00047702
      - 0.00045201
      - 0.00000732
      - 0.00000061
      - 0.00000061
      - 0.00000427
      - 0.00022814
      - 0.00010431
      - 0.00000061
      - 0.00595970
      - 0.00009943
      - 0.00000000
      - 0.00008174
      - 0.00013359
      - 0.00017751
      - 0.00484279
      - 0.00008906
      - 0.00000061
      - 0.00002440
      - 0.00480375
      - 0.00002379
      - 0.00000244
      - 0.00026413
      - 0.00000488
      - 0.00054168
      - 0.00072468
      - 0.00000976
      - 0.00037332
      - 0.00001586
      - 0.00024583
      - 0.00004636
      - 0.00006771
      - 0.00000305
      - 0.00088206
      - 0.00000061
      - 0.00001525
      - 0.00002623
      - 0.00003111
      - 0.00002806
      - 0.00000183
      - 0.00041358
      - 0.00000061
      - 0.00210938
      - 0.00000000
      - 0.00007503
      - 0.00011285
      - 0.00000427
      - 0.00000854
      - 0.00007930
      - 0.00001403
      pad_samples_to_global_batch_size: false
      return_positions: true
      token_size_in_bytes: 4
      tokenizer_name: HuggingFaceTB/SmolLM3-3B
      use_old_brrr_dataloader: false
      vocab_size: 128256
    num_loading_workers: 0
    seed: 6
  name: stable
  start_training_step: 1
general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: true
  project: smollm3
  run: baseline
  seed: 6
  step: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
model:
  ddp_bucket_cap_mb: 50
  dtype: bfloat16
  init_method:
    std: 0.02
  make_vocab_size_divisible_by: 1
  model_config:
    _attn_implementation: flash_attention_2
    _fused_rms_norm: true
    _fused_rotary_emb: true
    _use_doc_masking: false
    _use_qkv_packed: true
    attention_bias: false
    bos_token_id: 128000
    eos_token_id: 128001
    flex_attention_mask: null
    hidden_act: silu
    hidden_size: 1536
    initializer_range: 0.02
    intermediate_size: 4096
    is_qwen2_config: true
    max_position_embeddings: 4096
    moe_config: null
    num_attention_heads: 12
    num_hidden_layers: 36
    num_key_value_heads: 4
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-05
    rope_interleaved: false
    rope_scaling: null
    rope_theta: 50000.0
    sliding_window_size: null
    tie_word_embeddings: true
    use_cache: true
    vocab_size: 128256
    no_rope_layer: null
optimizer:
  accumulate_grad_in_fp32: true
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.0005
    lr_decay_starting_step: 9000
    lr_decay_steps: 1000
    lr_decay_style: cosine
    lr_warmup_steps: 1000
    lr_warmup_style: linear
    min_decay_lr: 5.0e-05
  optimizer_factory:
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    name: adamW
    torch_adam_is_fused: true
  weight_decay: 0.1
  weight_decay_exclude_named_params: null
  zero_stage: 0
parallelism:
  context_parallel_size: 1
  dp: 4
  expert_parallel_size: 1
  moe_layer_recompute: false
  pp: 1
  pp_engine: 1f1b
  recompute_layer: false
  tp: 1
  tp_linear_async_communication: true
  tp_mode: REDUCE_SCATTER
  tp_recompute_allgather: true
profiler: null
s3_upload: null
tokenizer:
  tokenizer_max_length: 4096
  tokenizer_name_or_path: HuggingFaceTB/SmolLM3-3B
  tokenizer_revision: null
metrics_logging:
  log_level: 1
  log_detail_interval: 100
tokens:
  batch_accumulation_per_replica: 64
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 2
  sequence_length: 4096
  train_steps: 500
  val_check_interval: 100
