checkpoints:
  checkpoint_interval: 2000
  checkpoints_path: /path/to/models/verify-ppt/marin_100b_7b
  checkpoints_path_is_shared_file_system: false
  load_lr_scheduler: true
  load_optimizer: true
  resume_checkpoint_path: null
  save_final_state: true
  save_initial_state: false
data_stages:
- data:
    dataset:
      dataset_folder:
      - /path/to/data/marin/dclm_marin_103b
      - /path/to/data/marin/proof-pile-algebraic-stack
      - /path/to/data/marin/proof-pile-arxiv
      - /path/to/data/marin/proof-pile-open-web-math
      - /path/to/data/marin/starcoderdata_ada
      - /path/to/data/marin/starcoderdata_agda
      - /path/to/data/marin/starcoderdata_alloy
      - /path/to/data/marin/starcoderdata_antlr
      - /path/to/data/marin/starcoderdata_applescript
      - /path/to/data/marin/starcoderdata_assembly
      - /path/to/data/marin/starcoderdata_augeas
      - /path/to/data/marin/starcoderdata_awk
      - /path/to/data/marin/starcoderdata_batchfile
      - /path/to/data/marin/starcoderdata_bluespec
      - /path/to/data/marin/starcoderdata_c-sharp
      - /path/to/data/marin/starcoderdata_c
      - /path/to/data/marin/starcoderdata_clojure
      - /path/to/data/marin/starcoderdata_cmake
      - /path/to/data/marin/starcoderdata_coffeescript
      - /path/to/data/marin/starcoderdata_common-lisp
      - /path/to/data/marin/starcoderdata_cpp
      - /path/to/data/marin/starcoderdata_css
      - /path/to/data/marin/starcoderdata_cuda
      - /path/to/data/marin/starcoderdata_dart
      - /path/to/data/marin/starcoderdata_dockerfile
      - /path/to/data/marin/starcoderdata_elixir
      - /path/to/data/marin/starcoderdata_elm
      - /path/to/data/marin/starcoderdata_emacs-lisp
      - /path/to/data/marin/starcoderdata_erlang
      - /path/to/data/marin/starcoderdata_f-sharp
      - /path/to/data/marin/starcoderdata_fortran
      - /path/to/data/marin/starcoderdata_git-commits-cleaned
      - /path/to/data/marin/starcoderdata_github-issues-filtered-structured
      - /path/to/data/marin/starcoderdata_glsl
      - /path/to/data/marin/starcoderdata_go
      - /path/to/data/marin/starcoderdata_groovy
      - /path/to/data/marin/starcoderdata_haskell
      - /path/to/data/marin/starcoderdata_html
      - /path/to/data/marin/starcoderdata_idris
      - /path/to/data/marin/starcoderdata_isabelle
      - /path/to/data/marin/starcoderdata_java-server-pages
      - /path/to/data/marin/starcoderdata_java
      - /path/to/data/marin/starcoderdata_javascript
      - /path/to/data/marin/starcoderdata_json
      - /path/to/data/marin/starcoderdata_julia
      - /path/to/data/marin/starcoderdata_jupyter-scripts-dedup-filtered
      - /path/to/data/marin/starcoderdata_jupyter-structured-clean-dedup
      - /path/to/data/marin/starcoderdata_kotlin
      - /path/to/data/marin/starcoderdata_lean
      - /path/to/data/marin/starcoderdata_literate-agda
      - /path/to/data/marin/starcoderdata_literate-coffeescript
      - /path/to/data/marin/starcoderdata_literate-haskell
      - /path/to/data/marin/starcoderdata_lua
      - /path/to/data/marin/starcoderdata_makefile
      - /path/to/data/marin/starcoderdata_maple
      - /path/to/data/marin/starcoderdata_markdown
      - /path/to/data/marin/starcoderdata_mathematica
      - /path/to/data/marin/starcoderdata_matlab
      - /path/to/data/marin/starcoderdata_ocaml
      - /path/to/data/marin/starcoderdata_pascal
      - /path/to/data/marin/starcoderdata_perl
      - /path/to/data/marin/starcoderdata_php
      - /path/to/data/marin/starcoderdata_powershell
      - /path/to/data/marin/starcoderdata_prolog
      - /path/to/data/marin/starcoderdata_protocol-buffer
      - /path/to/data/marin/starcoderdata_python
      - /path/to/data/marin/starcoderdata_r
      - /path/to/data/marin/starcoderdata_racket
      - /path/to/data/marin/starcoderdata_restructuredtext
      - /path/to/data/marin/starcoderdata_rmarkdown
      - /path/to/data/marin/starcoderdata_ruby
      - /path/to/data/marin/starcoderdata_rust
      - /path/to/data/marin/starcoderdata_sas
      - /path/to/data/marin/starcoderdata_scala
      - /path/to/data/marin/starcoderdata_scheme
      - /path/to/data/marin/starcoderdata_shell
      - /path/to/data/marin/starcoderdata_smalltalk
      - /path/to/data/marin/starcoderdata_solidity
      - /path/to/data/marin/starcoderdata_sparql
      - /path/to/data/marin/starcoderdata_sql
      - /path/to/data/marin/starcoderdata_stan
      - /path/to/data/marin/starcoderdata_standard-ml
      - /path/to/data/marin/starcoderdata_stata
      - /path/to/data/marin/starcoderdata_systemverilog
      - /path/to/data/marin/starcoderdata_tcl
      - /path/to/data/marin/starcoderdata_tcsh
      - /path/to/data/marin/starcoderdata_tex
      - /path/to/data/marin/starcoderdata_thrift
      - /path/to/data/marin/starcoderdata_typescript
      - /path/to/data/marin/starcoderdata_verilog
      - /path/to/data/marin/starcoderdata_vhdl
      - /path/to/data/marin/starcoderdata_visual-basic
      - /path/to/data/marin/starcoderdata_xslt
      - /path/to/data/marin/starcoderdata_yacc
      - /path/to/data/marin/starcoderdata_yaml
      - /path/to/data/marin/starcoderdata_zig
      dataset_read_path:
      - /path/to/data/marin/dclm_marin_103b
      - /path/to/data/marin/proof-pile-algebraic-stack
      - /path/to/data/marin/proof-pile-arxiv
      - /path/to/data/marin/proof-pile-open-web-math
      - /path/to/data/marin/starcoderdata_ada
      - /path/to/data/marin/starcoderdata_agda
      - /path/to/data/marin/starcoderdata_alloy
      - /path/to/data/marin/starcoderdata_antlr
      - /path/to/data/marin/starcoderdata_applescript
      - /path/to/data/marin/starcoderdata_assembly
      - /path/to/data/marin/starcoderdata_augeas
      - /path/to/data/marin/starcoderdata_awk
      - /path/to/data/marin/starcoderdata_batchfile
      - /path/to/data/marin/starcoderdata_bluespec
      - /path/to/data/marin/starcoderdata_c-sharp
      - /path/to/data/marin/starcoderdata_c
      - /path/to/data/marin/starcoderdata_clojure
      - /path/to/data/marin/starcoderdata_cmake
      - /path/to/data/marin/starcoderdata_coffeescript
      - /path/to/data/marin/starcoderdata_common-lisp
      - /path/to/data/marin/starcoderdata_cpp
      - /path/to/data/marin/starcoderdata_css
      - /path/to/data/marin/starcoderdata_cuda
      - /path/to/data/marin/starcoderdata_dart
      - /path/to/data/marin/starcoderdata_dockerfile
      - /path/to/data/marin/starcoderdata_elixir
      - /path/to/data/marin/starcoderdata_elm
      - /path/to/data/marin/starcoderdata_emacs-lisp
      - /path/to/data/marin/starcoderdata_erlang
      - /path/to/data/marin/starcoderdata_f-sharp
      - /path/to/data/marin/starcoderdata_fortran
      - /path/to/data/marin/starcoderdata_git-commits-cleaned
      - /path/to/data/marin/starcoderdata_github-issues-filtered-structured
      - /path/to/data/marin/starcoderdata_glsl
      - /path/to/data/marin/starcoderdata_go
      - /path/to/data/marin/starcoderdata_groovy
      - /path/to/data/marin/starcoderdata_haskell
      - /path/to/data/marin/starcoderdata_html
      - /path/to/data/marin/starcoderdata_idris
      - /path/to/data/marin/starcoderdata_isabelle
      - /path/to/data/marin/starcoderdata_java-server-pages
      - /path/to/data/marin/starcoderdata_java
      - /path/to/data/marin/starcoderdata_javascript
      - /path/to/data/marin/starcoderdata_json
      - /path/to/data/marin/starcoderdata_julia
      - /path/to/data/marin/starcoderdata_jupyter-scripts-dedup-filtered
      - /path/to/data/marin/starcoderdata_jupyter-structured-clean-dedup
      - /path/to/data/marin/starcoderdata_kotlin
      - /path/to/data/marin/starcoderdata_lean
      - /path/to/data/marin/starcoderdata_literate-agda
      - /path/to/data/marin/starcoderdata_literate-coffeescript
      - /path/to/data/marin/starcoderdata_literate-haskell
      - /path/to/data/marin/starcoderdata_lua
      - /path/to/data/marin/starcoderdata_makefile
      - /path/to/data/marin/starcoderdata_maple
      - /path/to/data/marin/starcoderdata_markdown
      - /path/to/data/marin/starcoderdata_mathematica
      - /path/to/data/marin/starcoderdata_matlab
      - /path/to/data/marin/starcoderdata_ocaml
      - /path/to/data/marin/starcoderdata_pascal
      - /path/to/data/marin/starcoderdata_perl
      - /path/to/data/marin/starcoderdata_php
      - /path/to/data/marin/starcoderdata_powershell
      - /path/to/data/marin/starcoderdata_prolog
      - /path/to/data/marin/starcoderdata_protocol-buffer
      - /path/to/data/marin/starcoderdata_python
      - /path/to/data/marin/starcoderdata_r
      - /path/to/data/marin/starcoderdata_racket
      - /path/to/data/marin/starcoderdata_restructuredtext
      - /path/to/data/marin/starcoderdata_rmarkdown
      - /path/to/data/marin/starcoderdata_ruby
      - /path/to/data/marin/starcoderdata_rust
      - /path/to/data/marin/starcoderdata_sas
      - /path/to/data/marin/starcoderdata_scala
      - /path/to/data/marin/starcoderdata_scheme
      - /path/to/data/marin/starcoderdata_shell
      - /path/to/data/marin/starcoderdata_smalltalk
      - /path/to/data/marin/starcoderdata_solidity
      - /path/to/data/marin/starcoderdata_sparql
      - /path/to/data/marin/starcoderdata_sql
      - /path/to/data/marin/starcoderdata_stan
      - /path/to/data/marin/starcoderdata_standard-ml
      - /path/to/data/marin/starcoderdata_stata
      - /path/to/data/marin/starcoderdata_systemverilog
      - /path/to/data/marin/starcoderdata_tcl
      - /path/to/data/marin/starcoderdata_tcsh
      - /path/to/data/marin/starcoderdata_tex
      - /path/to/data/marin/starcoderdata_thrift
      - /path/to/data/marin/starcoderdata_typescript
      - /path/to/data/marin/starcoderdata_verilog
      - /path/to/data/marin/starcoderdata_vhdl
      - /path/to/data/marin/starcoderdata_visual-basic
      - /path/to/data/marin/starcoderdata_xslt
      - /path/to/data/marin/starcoderdata_yacc
      - /path/to/data/marin/starcoderdata_yaml
      - /path/to/data/marin/starcoderdata_zig
      dataset_weights:
      - 0.92600
      - 0.00260
      - 0.00685
      - 0.00355
      - 0.00002074
      - 0.00000549
      - 0.00000061
      - 0.00000427
      - 0.00000061
      - 0.00012383
      - 0.00000000
      - 0.00000183
      - 0.00001830
      - 0.00000244
      - 0.00355203
      - 0.00428647
      - 0.00003660
      - 0.00003599
      - 0.00005063
      - 0.00011163
      - 0.00389119
      - 0.00023851
      - 0.00004453
      - 0.00029097
      - 0.00003355
      - 0.00005673
      - 0.00002379
      - 0.00003233
      - 0.00005551
      - 0.00004880
      - 0.00014152
      - 0.00254492
      - 0.00432673
      - 0.00003172
      - 0.00189161
      - 0.00007259
      - 0.00017751
      - 0.00233508
      - 0.00000244
      - 0.00000610
      - 0.00007808
      - 0.00691496
      - 0.00514657
      - 0.00007930
      - 0.00010431
      - 0.00056608
      - 0.00047702
      - 0.00045201
      - 0.00000732
      - 0.00000061
      - 0.00000061
      - 0.00000427
      - 0.00022814
      - 0.00010431
      - 0.00000061
      - 0.00595970
      - 0.00009943
      - 0.00000000
      - 0.00008174
      - 0.00013359
      - 0.00017751
      - 0.00484279
      - 0.00008906
      - 0.00000061
      - 0.00002440
      - 0.00480375
      - 0.00002379
      - 0.00000244
      - 0.00026413
      - 0.00000488
      - 0.00054168
      - 0.00072468
      - 0.00000976
      - 0.00037332
      - 0.00001586
      - 0.00024583
      - 0.00004636
      - 0.00006771
      - 0.00000305
      - 0.00088206
      - 0.00000061
      - 0.00001525
      - 0.00002623
      - 0.00003111
      - 0.00002806
      - 0.00000183
      - 0.00041358
      - 0.00000061
      - 0.00210938
      - 0.00000000
      - 0.00007503
      - 0.00011285
      - 0.00000427
      - 0.00000854
      - 0.00007930
      - 0.00001403
      pad_samples_to_global_batch_size: false
      return_positions: true
      token_size_in_bytes: 4
      tokenizer_name: HuggingFaceTB/SmolLM3-3B
      use_old_brrr_dataloader: false
      vocab_size: 128256
    num_loading_workers: 0
    seed: 6
  name: stable
  start_training_step: 1
general:
  benchmark_csv_path: null
  consumed_train_samples: null
  ignore_sanity_checks: true
  project: smollm3
  run: baseline
  seed: 6
  step: null
logging:
  iteration_step_info_interval: 1
  log_level: info
  log_level_replica: info
model:
  ddp_bucket_cap_mb: 50
  dtype: bfloat16
  init_method:
    std: 0.02
  make_vocab_size_divisible_by: 1
  model_config:
    _attn_implementation: flash_attention_2
    _fused_rms_norm: true
    _fused_rotary_emb: true
    _use_doc_masking: false
    _use_qkv_packed: true
    attention_bias: false
    bos_token_id: 128000
    eos_token_id: 128001
    flex_attention_mask: null
    hidden_act: silu
    hidden_size: 3584
    initializer_range: 0.02
    intermediate_size: 18944
    is_qwen2_config: true
    max_position_embeddings: 4096
    moe_config: null
    num_attention_heads: 28
    num_hidden_layers: 28
    num_key_value_heads: 4
    pad_token_id: null
    pretraining_tp: 1
    rms_norm_eps: 1.0e-06
    rope_interleaved: false
    rope_scaling: null
    rope_theta: 50000.0
    sliding_window_size: null
    tie_word_embeddings: true
    use_cache: true
    vocab_size: 128256
    no_rope_layer: null
    log_attn_probs: false
optimizer:
  accumulate_grad_in_fp32: true
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.0003
    lr_decay_starting_step: 42916
    lr_decay_steps: 4768
    lr_decay_style: cosine
    lr_warmup_steps: 2000
    lr_warmup_style: linear
    min_decay_lr: 3.0e-05
  optimizer_factory:
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    name: flash_adamw
    torch_adam_is_fused: false
  weight_decay: 0.1
  weight_decay_exclude_named_params: null
  zero_stage: 0
parallelism:
  context_parallel_size: 1
  dp: 256
  expert_parallel_size: 1
  moe_layer_recompute: false
  pp: 1
  pp_engine: 1f1b
  recompute_layer: true
  tp: 2
  tp_linear_async_communication: true
  tp_mode: REDUCE_SCATTER
  tp_recompute_allgather: true
profiler: null
s3_upload: null
tokenizer:
  tokenizer_max_length: 4096
  tokenizer_name_or_path: HuggingFaceTB/SmolLM3-3B
  tokenizer_revision: null
metrics_logging:
  log_level: 0
  log_detail_interval: 100
tokens:
  batch_accumulation_per_replica: 1
  limit_test_batches: 0
  limit_val_batches: 0
  micro_batch_size: 2
  sequence_length: 4096
  train_steps: 47684
  val_check_interval: 100
